### ISSUE TITLE
Errors in analysis functions are catched and passed as input to `Summarise` when there are multiple analysis functions

### ISSUE THREAD

**Issue by marklhc** [philchalmers/SimDesign#18]
Hi @philchalmers, thank you so much for adding the capacity to handle multiple analysis functions, which I think is really a game-changer as I usually need to compare multiple methods applied to the same data set! As I'm trying it out, however, I run into an issue in that when one of the analysis functions throw an error, it does not stop the program or regenerate a new data set, like what it typically does when there is a single analysis function. Instead, it seems the error is captured using `tryCatch()` (or `try()`), and is included in the `results` object passed to the `Summarise` function. Here's a reproducible example that I adapted from [this vignette](https://cran.r-project.org/web/packages/SimDesign/vignettes/Catch_errors.html):

``` r
library(SimDesign)
# SimFunctions(comments=FALSE)

Design <- createDesign(N = c(10, 20, 30))

Generate <- function(condition, fixed_objects = NULL) {
    ret <- with(condition, rnorm(N))
    ret
}

Analyse.a1 <- function(condition, dat, fixed_objects = NULL) {
    whc <- sample(c(0, 1, 2, 3), 1, prob = c(.7, .20, .05, .05))
    if (whc == 0) {
        ret <- mean(dat)
    } else if (whc == 1) {
        ret <- t.test() # missing arguments
    } else if (whc == 2) {
        ret <- t.test("invalid") # invalid arguments
    } else if (whc == 3) {
        # throw error manually
        stop("Manual error thrown")
    }
    # manual warnings
    if (sample(c(TRUE, FALSE), 1, prob = c(.1, .9))) {
        warning("This warning happens rarely")
    }
    if (sample(c(TRUE, FALSE), 1, prob = c(.5, .5))) {
        warning("This warning happens much more often")
    }
    ret
}

Analyse.a2 <- function(condition, dat, fixed_objects = NULL) {
    ret <- median(dat)
    ret
}

Summarise <- function(condition, results, fixed_objects = NULL) {
    ret <- c(bias = bias(results, 0))
    ret
}

result <- runSimulation(Design,
                        replications = 10, seed = rep(103, 3),
                        generate = Generate, analyse = list(a1 = Analyse.a1, a2 = Analyse.a2), summarise = Summarise
)
#> 
#> Design row: 1/3;   Started: Tue Aug 17 11:32:50 2021;   Total elapsed time: 0.00s
#> Error: Summarise() should not throw errors. Message was:
#>     Error in t(estimate) - parameter : 
#>   non-numeric argument to binary operator
```

<sup>Created on 2021-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I think this is not the intended behavior but maybe I'm mistaken. Would you mind taking a look? Thanks so much. 

Mark

**Comment by philchalmers** [comment]
Hi @marklhc thanks for the report, and glad you like the new feature (despite the bug!). I was contemplating adding something similar for the `summarise` argument but realized that doing so would just result in running independent simulation studies (but with more steps that only add complexity ;-) ). The analyse list is a bit of fresh air though for much more involved simulations. 

The output indeed is not the intended behaviour as it should give the same result as a single `Analyse()` definition. The culprit was that a `list` of caught-errors were being returned, where instead it should have just return the resulting error message the instant that it was caught (mimicking what the single definition would do). 

I also noticed that the resulting Warning and Error messages weren't as clean as they should be when using `SimExtract()`, so that's been patched too. Let me know if the dev version fixes things on your end!

**Comment by marklhc** [comment]
Hi @philchalmers thank you so much for fixing it so quickly! I updated the package and it runs great now!
