### ISSUE TITLE
Improve documentation on parallel processing

### ISSUE THREAD

**Issue by mronkko** [philchalmers/SimDesign#32]
The documentation on parallel processing could be improved by explaining on which level parallelization is done. Is it done on the simulation desing level, on the replication level, or both? The current documentation and the 2020 article leave this unexplained.

**Comment by philchalmers** [comment]
It's always on the replication level, otherwise the progress being presented wouldn't work as they do. I'll make a note about this in the documentation, but it's quite minor.

**Comment by mronkko** [comment]
Can you make it optionally work on the design level? If I have replications that run fairly quickly, overhead might become an issue, and it would be more efficient to parallelize on the design level.

**Comment by philchalmers** [comment]
I'll consider adding support for this, though my gut reaction is that such a feature could add a great deal of code complication under the hood. I'll leave the issue open for now until I have time to look into this further.

**Comment by philchalmers** [comment]
Looking over the current codebase this would indeed take a large number of changes for very little added functionality. In my experience most of the overhead of simulations comes from the replication steps instead of the major design conditions, which is why the package is designed the way it is. Moreover, because the simulation conditions being looped over are likely supplying different computational intensity (e.g., increasing sample sizes from small to large) the distribution of parallel processing resources would require a great deal of tweaking to best balance the load distribution. 

What I would consider adding, however, is more specificity in the per condition parallel distribution resources. For example, rather than having  `runSimulation(..., parallel=TRUE)` the `parallel` argument could instead be vectorized to indicate that some conditions should use parallel processing (e.g., large sample size, complex models) while others should not (small sample size, simple models). Would this help in your situation?

**Comment by mronkko** [comment]
You are probably right. This is more about a general design principle than a practical concern: parallelization should generally be done as early as possible in code to reduce overhead. Maybe this is something to be considered for version 3? The issue can also be solved by calling ´´´runSimulation(...,  parallel = FALSE)´´´and implementing parallelization in the user code.
