### ISSUE TITLE
Seeds and reproducibility in distributed simulations

### ISSUE THREAD

**Issue by mronkko** [philchalmers/SimDesign#37]
A simulation may not fully complete when running on an HPC cluster because of the cluster's time limits. The currently recommended workflow is to check the missing replications, add more rows to the design matrix, and rerun with a new set of arrayIDs. This may need to be repeated several times.

This workflow is problematic for reproducibility because it would require the user to keep track of which runs each replication originates from. 

Storing the random number generator state before each replication is one way to solve this problem, but it is impractical with very large simulations.

I propose three changes to make reproducibility easier:

### 1) Implement replication number

Large simulations can now run replications as smaller sets. For example, if we run 1000 reps, this can run as 10 sets of 100 replications using `expandDesign()'. This complicates the management of replications because the aggregated results do not clearly indicate which run each replication originated from.

I propose a new function that adds replication numbers to the design. The replication number would be stored as a new column, `replications`, that contains a vector of two or more elements. If the vector contains two elements, it is interpreted as a range where the first element is the first replication number and the second element is the final replication number. If the vector has more than two elements, it is interpreted as a vector of replications to be run.

Here is a proposed implementation

```

library(SimDesign)

Design <- createDesign(N = c(10, 20, 30))

# Add design numbers, this is needed for adding replication numbers

Design <- tibble::add_column(Design, 
                             design = 1:nrow(Design),
                             .before = 1)

Generate <- function(condition, fixed_objects = NULL) {
    dat <- with(condition, rnorm(N, 10, 5)) # distributed N(10, 5)
    dat
}

Analyse <- function(condition, dat, fixed_objects = NULL) {
    ret <- c(mean=mean(dat), median=median(dat)) # mean/median of sample data
    ret
}

Summarise <- function(condition, results, fixed_objects = NULL){
    colMeans(results)
}

expandDesign <- function(Design, repeat_conditions){
    stopifnot(!missing(Design))
    stopifnot(!missing(repeat_conditions))
    if(length(repeat_conditions) == 1L)
        repeat_conditions <- rep(repeat_conditions, nrow(Design))
    stopifnot("length of repeat_rows must equal number of rows in final object"=
                  length(repeat_conditions) == nrow(Design))
    ret <- Design[sort(rep(1L:nrow(Design), times=repeat_conditions)), ]
    rownames(ret) <- NULL
    
    ret
}

addReplicationsToDesign <- function(ExpandedDesign, replications){
    stopifnot(!missing(ExpandedDesign))
    stopifnot(!missing(replications))

    ExpandedDesign %>%
        group_by(design) %>%
        group_modify(function(.x, .y){
            
            # Split the replications in sets
            replicationSets <- split(1:replications,
                                     cut(1:replications, nrow(.x),
                                         labels = FALSE))
            # Then return ranges
            ret <- tibble(replications = lapply(replicationSets, range))
            ret
        })
}

# expand the design to create 300 rows with associated replications
Design300 <- expandDesign(Design, repeat_conditions = 100L)
DesignWithReplications <- addReplicationsToDesign(Design300, replications = 10000L)
DesignWithReplications
```

If the simulation design contains the `replications` column, it should override the replications argument of the `runSimulation()` function.

### 2) Add design number and replication number to each set of results

When we print out the raw simulation results, the output should look like this:

```
# A tibble: 180 × 7
   design_number replication_number sample_size group_size_ratio standard_deviation_r…¹  welch independent
           <int>              <int>       <dbl>            <dbl>                  <dbl>  <dbl>       <dbl>
 1             1                  1          30                1                    0.5 0.850       0.849 
 2             1                  2          30                1                    0.5 0.574       0.573 
 3             1                  3          30                1                    0.5 0.945       0.944 
 4             1                  4          30                1                    0.5 0.0910      0.0883
 5             1                  5          30                1                    0.5 0.0365      0.0329
 6             2                  1          60                1                    0.5 0.819       0.819 
 7             2                  2          60                1                    0.5 0.355       0.354 
 8             2                  3          60                1                    0.5 0.586       0.585 
 9             2                  4          60                1                    0.5 0.671       0.670 
10             2                  5          60                1                    0.5 0.285       0.283 
```

Adding design numbers is easy in the user code, but adding replication numbers is not.  The code to produce this example is 

```
Design <- createDesign(sample_size = c(30, 60, 90, 120),
                       group_size_ratio = c(1, 4, 8),
                       standard_deviation_ratio = c(.5, 1, 2))
Design

# THIS SHOULD BE ADDED AUTOMATICALLY
Design <- tibble::add_column(Design, 
                             design_number = 1:nrow(Design),
                             .before = 1)

#~~~~~~~~~~~~~~~~~~~~~~~~
#### Step 2 --- Define generate, analyse, and summarise functions

Generate <- function(condition, fixed_objects = NULL) {
    N <- condition$sample_size      # could use Attach() to make objects available
    grs <- condition$group_size_ratio
    sd <- condition$standard_deviation_ratio
    if(grs < 1){
        N2 <- N / (1/grs + 1)
        N1 <- N - N2
    } else {
        N1 <- N / (grs + 1)
        N2 <- N - N1
    }
    group1 <- rnorm(N1)
    group2 <- rnorm(N2, sd=sd)
    dat <- data.frame(group = c(rep('g1', N1), rep('g2', N2)), DV = c(group1, group2))
    dat
}

Analyse <- function(condition, dat, fixed_objects = NULL) {
    welch <- t.test(DV ~ group, dat)$p.value
    independent <- t.test(DV ~ group, dat, var.equal=TRUE)$p.value
    
    # In this function the p values for the t-tests are returned,
    #  and make sure to name each element, for future reference
    ret <- nc(welch, independent)
    ret
}

Summarise <- function(condition, results, fixed_objects = NULL) {
    #find results of interest here (e.g., alpha < .1, .05, .01)
    ret <- EDR(results, alpha = .05)
    ret
}


#~~~~~~~~~~~~~~~~~~~~~~~~
#### Step 3 --- Collect results by looping over the rows in design

# first, test to see if it works
res <- runSimulation(design=Design, replications=5,
                     generate=Generate, analyse=Analyse)
res

# ADD REPLICATION NUMBERS LIKE THIS IN runSimulation

tibble::add_column(res, 
                   replication_number = rep(1:5, nrow(Design)),
                   .after = 1)
```

### 3) Use RNG substreams

Parallel computation is currently implemented with L'Ecuyer-CMRG's (2002) method. This method supports RNG streams that can each have a substream [https://stat.ethz.ch/R-manual/R-devel/library/parallel/html/RngStream.html](https://stat.ethz.ch/R-manual/R-devel/library/parallel/html/RngStream.html). The current implementation uses streams on the design level. I propose using substreams on a replication level.

One way to implement this would be to have the `seed` argument to also accept functions that set the RNG state for each replication: `seed = function(design, replication)`. This would allow the user to specify their own seed generating functions on a replication level. One useful  function would be

```
function(design, replication){
    nextRNGStream(design)
    nextRNGSubStream(replication)
}
```

This could be implemented also as a new argument accepting a function `initRNG = function(seed, design, replication)`

**Comment by philchalmers** [comment]
> This workflow is problematic for reproducibility because it would require the user to keep track of which runs each replication originates from.

Each condition in the expanded `Design` object is assigned a unique seed, which is iterated sequentially as the random numbers unfold, so at the very least each condition is inherently reproducible and with minimal effort. However, I see your point about the specificity of this approach being problematic in that if one wish to reproduce row 2 in the expanded design, replication number 42, that would require running all previous iterations in the sequence. 

I'll have to store another count object somewhere to replicate this information as the replication number itself will not correspond to the same sequence in the `.Random.seed` chain due to discarded replications within a `while(TRUE)` loop until a successful run occurs. This is something like what your point 3) is, though its unfortunately more nuanced, and ultimately will require additional arguments to add to `gen_seeds()`. I'll think about the most optimal approach to do this as I'm not completely sold on the current seed distribution approach used in `gen_seeds()`.

**Comment by philchalmers** [comment]
All except 3) should be addressed now. I didn't really see a use case for 1) though given that I have included the arrayID in 2), so you can rather easily get this information by doing something like 

```r
results <- SimResults(simobj)
subset(results, arrayID=42)
```
which will print all the output from arrayID 42, or if you a interested in the complete replication set for condition 3, for example, then
```r
results <- SimResults(simobj)
subset(results, condition=3)
```
in which case the replication number is just the respective row.

I'm less interested in the substream approach for within replication specificity largely because this is not present in the remaining areas of the package, and I don't see the major need for it anyway. Problematic seed results are still stored automatically and can be extracted and replicated in the same way within `runSimulation()`. And, as I mentioned earlier, each row in the expanded design objects are in principle reproducible, so in that sense the behavior is on par with the rest of the package.

**Comment by mronkko** [comment]
The use case for replication numbers is this (at least in my case): Sometimes, you might get a very unexpected result in one of the replications, and being able to refer to a replication with a unique identifier when discussing the results is useful because then your coauthor knows which exact part of the results to look at.

I am not sure if the current way of storing the random seeds addresses my use case. In our most recent project (https://psycnet.apa.org/doi/10.1037/met0000657) we had really bizarre results in some of the conditions and it was important to rerun them locally. These unexpected results were not errors, so the current implementation (as far as I know) would not have stored the RNG state automatically. 

I could run with save_seeds = TRUE, but I would prefer the substream approach because this means that there are less files to manage.

**Comment by philchalmers** [comment]
I see. If your unusual results threw warning messages than those seeds would have been caught and could have been reproduced locally, so if you could anticipate the unusual (but nonfatal) results and throw a warning that would be the best option. For the array distribution I actually don't mind adding options for complete seed restoring given that the objects themselves are likely to be smaller, and the seeds themselves (being of only length 7) will be easier to store. I'll add a `control = list(store_Random.seeds)` logical to allow for this, though of course it will be disabled by default.

**Comment by philchalmers** [comment]
Added. Option is effectively the same as `save_seeds` but stored internally per object. Only recommended for edge case debugging like the one your described. Each row of the returned seeds list from `SimExtract()` is associated with the results from `SimResults()` now, so you can track the information that way. HTH.

**Comment by mronkko** [comment]
That is helpful. The extra disk space requirement is trivial in most cases. 

Still, I think that replication numbers that are not dependent on how the results are sorted and RNG substreams would be useful features. For example, it might be possible (and this has happened to me) that there is a programming error that affects a subset of replications so that the results are incorrect but do not cause warnings or errors. In this case, identifying and rerunning specific replications would be useful. It would be possible to do this now with `control = list(store_Random.seeds = TRUE)` and then programming the simulation to rerun with these seeds. However, from the user's perspective, it would be a lot easier to just tell the simulations to rerun specific replications identified by a vector of replication numbers.  Replacing problematic replications with new independent replications is another solution, but that would be problematic because it may produce an unwanted selection effect in the results.

**Comment by philchalmers** [comment]
> In this case, identifying and rerunning specific replications would be useful.

Why? If the analyse portion is incorrect in some way then you have to rerun the simulation experiment, so there's nothing to be gained by using the exact same generated data as before (they would still be random samples, after all, and therefore unbiased draws from the population). If the issue is on the data generation step then the .Random.seed is irrelevant as the fixed Generate() function would provide different quality data then before, effectively no different than drawing from the population gain. If indeed there were artifacts being generated by using different .Random.seed states then this implies something is wrong with the experiment as then results depend on the distribution of randomness (hence, not i.i.d.), and the only answer would be to investigate more replications until the samples settle down.

> Replacing problematic replications with new independent replications is another solution, but that would be problematic because it may produce an unwanted selection effect in the results.

Again, I don't see how this could be problematic as this suggests something more nefarious at hand in the simulation experiment. In any event, I'm happy with the current implementation as it seems functional enough for the vast majority of applications and provides inlets to portions of the code to do more of the fine-grained replication stuff (with a bit of work, of course, but work that I don't believe offer much if any gains anyway).

**Comment by philchalmers** [comment]
FWY, added you as a pkg contributor (https://github.com/philchalmers/SimDesign/commit/b1650a3ca7d24bf19f5d462001db34acbd9b4f70) as this series of issues was heavily guided by our back-and-forth conversations.

**Comment by mronkko** [comment]
> FWY, added you as a pkg contributor (https://github.com/philchalmers/SimDesign/commit/b1650a3ca7d24bf19f5d462001db34acbd9b4f70) as this series of issues was heavily guided by our back-and-forth conversations.

Thanks!

**Comment by mronkko** [comment]
> > In this case, identifying and rerunning specific replications would be useful.
> 
> Why? If the analyse portion is incorrect in some way then you have to rerun the simulation experiment, so there's nothing to be gained by using the exact same generated data as before (they would still be random samples, after all, and therefore unbiased draws from the population).

There is saving time and computing costs. 

For example, in the paper that I cited above, we estimated a latent interaction model using ten different estimators and ran five different multivariate normality tests. The normality tests run very quickly, but some estimators take up to 30 min per replication in some conditions. When we were reporting the simulation results, we realized that some of the normality test results were unexpected and traced this down to a bug in the MVN package we used.

In this case, the normality tests were just a tiny fraction of the computational effort, and therefore, it made sense to run just these tests and not estimators that did not have any problem. We also used a different split of the computation to the nodes and ran one design per node instead of splitting the designs over multiple nodes as done when running the estimators.
 
In another project ([https://doi.org/10.1016/j.leaqua.2023.101733](https://doi.org/10.1016/j.leaqua.2023.101733)), we encountered non-convergent estimates. Inspecting these replications locally revealed that we could get these estimates to converge by tweaking the optimizer settings. Because our problem does not involve local maxima of likelihood (as far as we know), we concluded that changing optimizer settings will not affect the converged replications and rerun just the non-convergent ones.

I also remember a case where some of the replications failed because of exceeding the memory limit given to slurm. In this case, a job is killed by the cluster so that the R error handling code that would save the RNG state will not run. Because we managed the seeds by design and replication number, we were able to just continue running from where we left off after increasing the memory limit.

If computer resources were unlimited, rerunning the full simulation would be a lot easier option when sorting out this kind of issues. But when projects are months or even years of core time, rerunning it many times should be avoided.

**Comment by philchalmers** [comment]
> In this case, the normality tests were just a tiny fraction of the computational effort, and therefore, it made sense to run just these tests and not estimators that did not have any problem.

Quite the series of unfortunate events, though to me still feels like an exception rather than a rule. If anything I would imagine the bugs would be more likely to appear in the more computationally heavy portions of a simulation as there's frequently more moving parts to manage.

> In another project (https://doi.org/10.1016/j.leaqua.2023.101733), we encountered non-convergent estimates. Inspecting these replications locally revealed that we could get these estimates to converge by tweaking the optimizer settings. Because our problem does not involve local maxima of likelihood (as far as we know), we concluded that changing optimizer settings will not affect the converged replications and rerun just the non-convergent ones.

Modifying optimizer settings does affect the converged results too in that they have the potential to terminate in different locations of the objective function. However, if you're using an "if-then" logic where the initial model use the default optimizer settings and, if it failed to converge, then you use alternative optimizer criteria. In the if-then approach I see your point, though my gut reaction is to say that this was missed in the planning stage of the experiment where proper contingencies were not setup, and that falls on the experimenters side of the code base. 

In any case, I don't see a major problem in just accepting the originally converged simulation results (say again, 55/100) and running a new simulation condition with the fixed code for the remaining 45 non-converged conditions with the updated if-then logic. The models have to be re-estimated anyway with the new optimizer settings, and some of the models may even converge correctly given the new generated data, but for those that do not they would use the "then" portion of the logic where needed. The only major issue comes in the form of estimates of the probability of observing a non-converged model in the first place, which should only be based either on the original non-converged proportions (45/100) or, if there is further non-convergence logic happing in the new runs, then based on the if-then branch logic (e.g., without optimizer tweaks 22/45 models failed to converge; with optimizer tweaks, 5/45 failed to converge). The later circumstance is my main objection to using the originally generated data, for if the "then" portion fails to converge then you're back to redrawing data again, adding even more complication to the seed tracking than its worth. This why I'd prefer avoiding using the initial `.Random.seeds` from the 55/100 run because you would have to *guarantee* the optimizer tweaks will fix all the problem for every non-converged result, which is rather ambitious IMHO.

> I also remember a case where some of the replications failed because of exceeding the memory limit given to slurm. In this case, a job is killed by the cluster so that the R error handling code that would save the RNG state will not run. Because we managed the seeds by design and replication number, we were able to just continue running from where we left off after increasing the memory limit.

Well, not to be unfairly critical of historical work, but your seeds were managed via `set.seed()` which is not how one should be managing seeds at the replication-level as they are prone to generating redundant information, but point taken. As you're likely aware of at this point it's conceptually fine to do use `set.seed()` across different simulation conditions, but it's not okay to do this at the replications level as the conditional replications would not necessarily be i.i.d. (I've included this comment in case someone in the future is reading this thread and has made a similar mistake with `set.seed(replication_number)`).

W.r.t. RAM issues, this is indeed a problem I have yet to resolve in the package too. Probing total memory takes a non-trivial amount of overhead, and even detecting the maximum RAM on a computer is not something that is easy to do. I've thought about isolating simulation objects and checking their `object.size()` throughout the process, terminating if the objects get too large according to some definition provided by the user similar to how `max_time` is now used. Perhaps I should re-visit this topic now that `runArraySimulation()` becoming more mature.

> If computer resources were unlimited, rerunning the full simulation would be a lot easier option when sorting out this kind of issues. But when projects are months or even years of core time, rerunning it many times should be avoided.

Completely agree. I just don't see the necessity in utilizing the same random data when logic alternatives exist that in many cases have better (or at least, more nature) execution properties.
