### ISSUE TITLE
For-loop vs SimDesign issues

### ISSUE THREAD

**Issue by luca-scr** [philchalmers/SimDesign#5]
Hi, first I would like to congratulate with your very nice package. I don't know if I will use it in my simulations because I'm a long time user of the for-loop approach. However, your approach is very elegant.
I was reading your note at <http://philchalmers.github.io/SimDesign/html/12-What_not_2_do.html> 
and I guess your claim about the slow for-loop approach is mainly related to the fact that the matrix d is initialised as a NULL object and then updated each time by increasing the size of the matrix. That is something to absolutely avoid in R. The solution is simple, just define the matrix of the size needed and then assign the results to the matrix using an index for the row to update. 
For example:
```
# set nrows of matrix d
m = 2*length(N_list)*length(a_list)*length(b_list)*length(cp_list)*reps
# define matrix d
d = matrix(as.double(NA), nrow = m, ncol = 7)
idx = 0 # index to add results on rows of d
for (N in N_list){
    for (a in a_list){
        for (b in b_list){
            for (cp in cp_list){
                for (i in 1:reps){
                    X = rnorm(N, 0, 1)
                    M = a*X + rnorm(N, 0, 1)
                    Y = cp*X + b*M + rnorm(N, 0, 1)
                    idx <- idx+1
                    d[idx,] = c(i, a, b, cp, N, 1, sobel_test(X, M, Y))
                    idx <- idx+1
                    d[idx,] = c(i, a, b, cp, N, 2, sobel_test(X, Y, M))
                }
            }
        }
    }
}
colnames(d) = c("iteration", "a", "b", "cp", "N", "model", "Sobel_z")
d = data.frame(d)
```
I did a little experiment using `reps=100` and the time required  goes from 38 secs to 31 secs (about 20% faster), and I expect the speed up will be even much larger as the number of replications increases because in the old approach matrices of larger sizes have to be allocated each time.

Best,

Luca

**Comment by philchalmers** [comment]
Hi Luca,

Thanks for the comment. However, this code was a direct copy from a paper specifically on Monte Carlo simulations in R, so it's not mine (I'm well aware of this issue, though perhaps the authors of that paper were not). 

This does however highlight another idiosyncratic aspect of R, which is generally the point of why using `SimDesign` can be much better at the outset. I imagine hundreds of users have made this mistake in the past because they were not aware of this problem. Plus, with `SimDesign` you get *numerous* other benefits immediately, such as parallelization, error+warning tracking/handling, safe file saving mechanisms, restoration on power outages with temporary files, progress bars, and so on. Cheers.
