### ISSUE TITLE
[Refactorization] Merge Functionality with SimCollect?

### ISSUE THREAD

**Issue by emstruong** [philchalmers/SimDesign#51]
https://github.com/philchalmers/SimDesign/blob/97b4a4f1f28aa79ceb51b1d27b46d217ab27567e/R/reSummarise.R#L150-L163

When working with larger than memory replication results, being able to interface everything through SimCollect would be nice. As part of this, perhaps some of the functions could be refactored to work through SimCollect? 

We could narrow the surface on which the same kinds of bugs happen if everything were to go through SimCollect

**Comment by philchalmers** [comment]
Interesting RAM idea, though I don't think SimCollect would the right use in this case. The subset_results() function could go on line 153 though. 

My concern is that this could lead to more complicated tracking as some `summarise()` functions would not be applicable depending on the select subset, which somewhat goes against the 'avoiding hard to track' coding errors philosophy. I don't hate it in this context, it just feels a little uneasy given how much the complexity could grown.

**Comment by emstruong** [comment]
...Embarrassingly, I don't remember why I linked to the `reSummarise()` function. 

Well, IIRC, I was thinking that `SimCollect()` and `subset_results()` might have enough overlapping functionality to just merge them and generalize the functionality?

**Comment by philchalmers** [comment]
> ...Embarrassingly, I don't remember why I linked to the `reSummarise()` function.
> 
> Well, IIRC, I was thinking that `SimExtract()` and `subset_results()` might have enough overlapping functionality to just merge them and generalize the functionality?

They serve different functionality. SimExtract() could gain a `select` argument to perform the subsets, of course, but there's little need since if the entire simulation can be stored in RAM all at once (which is a prerequisite for SimExtract()) then subsets can be performed on the users side. Come to think of it, if `reSummarise()` is really having issues with range then `dplyr::select()` and related functions could be used within the call to the new summarise definition. I think closing this issue makes sense as I don't see the real issue.
